apiVersion: apps/v1
kind: Deployment
metadata:
  name: addui-service
  labels:
    app: addui-service
spec:
  selector:
    matchLabels:
      app: addui-service
  replicas: 1
  template:
    metadata:
      labels:
        app: addui-service
    spec:
      containers:
      - name: addui-service
        image: calquito/soa_p2
        imagePullPolicy: Always
        ports:
        - containerPort: 84
        env:
        - name: RABBIT_HOST 
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_PRODUCER_QUEUE
          value: "load-images"
