---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultsui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultsui-service
  template:
    metadata:
      labels:
        app: resultsui-service
    spec:
      containers:
        - name: resultsui-service
          image: acbdo/results-ui
          ports:
          - containerPort: 3000
          env:
          - name: REACT_APP_BACKEND 
            value: "127.0.0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: resultsui-service
spec:
  selector:
    app: resultsui-service
  ports:
  - port: 3000
    targetPort: 3000

    




