---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultsui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultsui-service
  template:
    metadata:
      labels:
        app: resultsui-service
    spec:
      containers:
        - name: resultsui-service
          image: acbdo/results-ui
          ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: resultsui-service
spec:
  type: NodePort
  selector:
    app: resultsui-service
  ports:
  - port: 3050
    targetPort: 3000
    protocol: TCP
    nodePort: 31000

    




