apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  selector:
    matchLabels:
      app: backend-service
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: nickotronz7/soa_p2_api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        - name: RABBIT_HOST 
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_CONSUMER_QUEUE
          value: "emotions-managment"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend-service
  ports:
    - protocol: TCP
      name: http
      port: 81
      targetPort: 81
