version: '2.2'
services:
  api:
    build: .
    container_name: "api"
    ports:
      - 10000:10000
    networks:
      api_network:
        aliases:
          - api_host
networks:
  api_network:
    name: api_net
    driver: bridge